server:
    port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dept?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password:
    jpa:
      show-sql: true
      properties:
        hibernate:
          formate_sql: true
